# AWS Prescriptive Guidance - Service Descriptions Template
# Enhanced with Cost Allocation and Compliance Focus
# Reference: https://docs.aws.amazon.com/prescriptive-guidance/latest/cost-allocation-tagging/
# Updated: 2025-08-08

service_descriptions:
  version: "1.0"
  compliance_framework: "AWS Prescriptive Guidance"
  last_updated: "2025-08-08"
  
  # Core AWS Services with Cost Allocation Focus
  services:
    # Compute Services
    ec2:
      name: "Amazon Elastic Compute Cloud"
      category: "Compute"
      cost_allocation_priority: "high"
      required_tags: ["CostCenter", "Project", "Environment", "BusinessUnit", "Application"]
      recommended_tags: ["TeamName", "AutoScaling", "ScheduledShutdown", "MaintenanceWindow"]
      description: "Scalable virtual servers in the cloud with granular cost tracking capabilities"
      cost_factors:
        - "Instance type and size"
        - "Operating system"
        - "Tenancy model"
        - "Reserved vs On-Demand pricing"
        - "EBS storage attached"
      governance_notes: "Critical for cost optimization - enable detailed monitoring for accurate cost allocation"
      
    s3:
      name: "Amazon Simple Storage Service"
      category: "Storage"
      cost_allocation_priority: "high"
      required_tags: ["CostCenter", "Project", "Environment", "BusinessUnit"]
      recommended_tags: ["DataClassification", "BackupRequired", "DataRetentionPeriod"]
      description: "Object storage with comprehensive cost tracking and lifecycle management"
      cost_factors:
        - "Storage class (Standard, IA, Glacier, etc.)"
        - "Data transfer costs"
        - "Request costs (GET, PUT, DELETE)"
        - "Data retrieval costs"
      governance_notes: "Implement lifecycle policies and cost allocation tags for optimal spend visibility"
      
    rds:
      name: "Amazon Relational Database Service"
      category: "Database"
      cost_allocation_priority: "high"
      required_tags: ["CostCenter", "Project", "Environment", "BusinessUnit", "Application"]
      recommended_tags: ["BackupRequired", "DisasterRecovery", "MaintenanceWindow", "EncryptionRequired"]
      description: "Managed relational databases with automated cost allocation and compliance tracking"
      cost_factors:
        - "Database engine and version"
        - "Instance class and size"
        - "Multi-AZ deployment"
        - "Backup and snapshot storage"
        - "Data transfer costs"
      governance_notes: "Essential for financial governance - track database costs per application and project"
      
    # Serverless and Container Services
    lambda:
      name: "AWS Lambda"
      category: "Compute"
      cost_allocation_priority: "medium"
      required_tags: ["CostCenter", "Project", "Environment", "BusinessUnit", "Application"]
      recommended_tags: ["ApplicationVersion", "TeamName"]
      description: "Serverless compute with pay-per-invocation cost model"
      cost_factors:
        - "Number of requests"
        - "Duration and memory allocation"
        - "Architecture (x86 vs ARM)"
      governance_notes: "Use function-level tagging for accurate serverless cost attribution"
      
    ecs:
      name: "Amazon Elastic Container Service"
      category: "Containers"
      cost_allocation_priority: "high"
      required_tags: ["CostCenter", "Project", "Environment", "BusinessUnit", "Application"]
      recommended_tags: ["TeamName", "AutoScaling", "ApplicationVersion"]
      description: "Container orchestration with granular resource cost tracking"
      cost_factors:
        - "Fargate vs EC2 launch type"
        - "CPU and memory allocation"
        - "Task count and duration"
      governance_notes: "Tag both services and tasks for comprehensive container cost visibility"
      
    # Networking Services
    vpc:
      name: "Amazon Virtual Private Cloud"
      category: "Network"
      cost_allocation_priority: "medium"
      required_tags: ["CostCenter", "BusinessUnit", "Environment"]
      recommended_tags: ["Application", "TeamName"]
      description: "Network isolation with associated data transfer and NAT gateway costs"
      cost_factors:
        - "NAT Gateway usage"
        - "VPC Endpoints"
        - "Data transfer between AZs"
        - "VPN connections"
      governance_notes: "Shared infrastructure - allocate costs based on primary use case or shared model"
      
    cloudfront:
      name: "Amazon CloudFront"
      category: "Network"
      cost_allocation_priority: "medium"
      required_tags: ["CostCenter", "Project", "BusinessUnit", "Application"]
      recommended_tags: ["Environment", "TeamName"]
      description: "Content delivery network with geographic cost distribution"
      cost_factors:
        - "Data transfer out to internet"
        - "Origin requests"
        - "Geographic distribution"
        - "Real-time logs"
      governance_notes: "Tag distributions for application-specific CDN cost tracking"
      
    # Analytics and Big Data
    redshift:
      name: "Amazon Redshift"
      category: "Analytics"
      cost_allocation_priority: "high"
      required_tags: ["CostCenter", "Project", "Environment", "BusinessUnit"]
      recommended_tags: ["DataClassification", "BackupRequired", "MaintenanceWindow"]
      description: "Data warehouse with predictable compute and storage costs"
      cost_factors:
        - "Node type and count"
        - "Reserved vs On-Demand pricing"
        - "Backup storage"
        - "Spectrum queries"
      governance_notes: "High-cost service requiring detailed project and cost center attribution"
      
    glue:
      name: "AWS Glue"
      category: "Analytics"
      cost_allocation_priority: "medium"
      required_tags: ["CostCenter", "Project", "Environment", "BusinessUnit"]
      recommended_tags: ["Application", "TeamName"]
      description: "Serverless ETL with job-based cost allocation"
      cost_factors:
        - "DPU hours consumed"
        - "Job type (Spark, Python shell)"
        - "Development endpoints"
      governance_notes: "Tag jobs and crawlers for accurate ETL cost attribution"
      
    # Security and Identity
    iam:
      name: "AWS Identity and Access Management"
      category: "Security"
      cost_allocation_priority: "low"
      required_tags: ["BusinessUnit", "Environment"]
      recommended_tags: ["Application", "TeamName"]
      description: "Identity management - minimal direct costs but critical for governance"
      cost_factors:
        - "Generally no direct costs"
        - "Some advanced features may have costs"
      governance_notes: "Tag roles and policies for security governance and compliance tracking"
      
    kms:
      name: "AWS Key Management Service"
      category: "Security"
      cost_allocation_priority: "low"
      required_tags: ["CostCenter", "Project", "BusinessUnit"]
      recommended_tags: ["Application", "DataClassification"]
      description: "Encryption key management with per-key and API call costs"
      cost_factors:
        - "Customer managed keys"
        - "API requests"
        - "Cross-region key usage"
      governance_notes: "Low cost but important for security compliance and audit trails"
      
    # Monitoring and Management
    cloudwatch:
      name: "Amazon CloudWatch"
      category: "Monitoring"
      cost_allocation_priority: "medium"
      required_tags: ["CostCenter", "BusinessUnit"]
      recommended_tags: ["Project", "Application", "Environment"]
      description: "Monitoring and observability with metrics, logs, and alarm costs"
      cost_factors:
        - "Custom metrics"
        - "Log ingestion and storage"
        - "API requests"
        - "Dashboard usage"
      governance_notes: "Distributed costs - allocate based on primary application or shared services model"
      
  # Cost Allocation Templates
  cost_allocation_templates:
    high_cost_services:
      description: "Services with significant cost impact requiring detailed tagging"
      services: ["ec2", "s3", "rds", "redshift", "ecs"]
      mandatory_tags: ["CostCenter", "Project", "Environment", "BusinessUnit", "Application"]
      reporting_frequency: "daily"
      
    medium_cost_services:
      description: "Services with moderate cost impact"
      services: ["lambda", "cloudfront", "glue", "cloudwatch", "vpc"]
      mandatory_tags: ["CostCenter", "Project", "BusinessUnit"]
      reporting_frequency: "weekly"
      
    low_cost_services:
      description: "Services with minimal cost impact but important for governance"
      services: ["iam", "kms"]
      mandatory_tags: ["BusinessUnit"]
      reporting_frequency: "monthly"
      
  # Compliance Mapping
  compliance_frameworks:
    aws_prescriptive_guidance:
      description: "AWS Prescriptive Guidance for Cost Allocation Tagging"
      requirements:
        - "Comprehensive tagging strategy"
        - "Cost center attribution"
        - "Project-based allocation"
        - "Environment segregation"
        - "Regular compliance monitoring"
      applicable_services: "all"
      
    aws_well_architected:
      description: "AWS Well-Architected Framework Cost Optimization Pillar"
      requirements:
        - "Cost-aware resource tagging"
        - "Spend visibility and tracking"
        - "Regular cost review processes"
      applicable_services: ["ec2", "s3", "rds", "redshift"]
      
  # Industry-Specific Configurations
  industry_templates:
    financial_services:
      additional_tags: ["ComplianceFramework", "DataClassification", "RegulatoryConcern"]
      enhanced_governance: true
      retention_requirements: "7 years"
      
    healthcare:
      additional_tags: ["PHI_Status", "HIPAA_Applicable", "PatientData"]
      enhanced_security: true
      encryption_required: true
      
    government:
      additional_tags: ["SecurityLevel", "AuthorityToOperate", "FISMA_Level"]
      enhanced_compliance: true
      audit_trail_required: true
      
  # Automation and Tooling Recommendations
  automation:
    tagging_automation:
      tools:
        - "AWS CloudFormation"
        - "AWS CDK"
        - "Terraform"
        - "AWS Service Catalog"
      best_practices:
        - "Infrastructure as Code with embedded tags"
        - "Automated tag inheritance"
        - "Tag validation in CI/CD pipelines"
        
    cost_monitoring:
      tools:
        - "AWS Cost Explorer"
        - "AWS Budgets"
        - "AWS Cost Anomaly Detection"
        - "Third-party cost management tools"
      key_metrics:
        - "Cost per project"
        - "Cost per environment"
        - "Cost per business unit"
        - "Untagged resource costs"
        
  # Reporting Templates
  cost_allocation_reports:
    executive_summary:
      frequency: "monthly"
      granularity: "business_unit"
      key_metrics:
        - "Total spend by business unit"
        - "Top 10 projects by cost"
        - "Environment cost distribution"
        - "Tag compliance percentage"
        
    project_detailed:
      frequency: "weekly"
      granularity: "project"
      key_metrics:
        - "Project spend trending"
        - "Service breakdown by project"
        - "Budget vs actual"
        - "Cost optimization opportunities"
        
    operational:
      frequency: "daily"
      granularity: "resource"
      key_metrics:
        - "Untagged resources"
        - "High-cost resources"
        - "Cost anomalies"
        - "Tag compliance violations"