blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://habhabhabs.github.io/inventag-aws/
    about: Check our comprehensive documentation for guides and examples
  - name: 💬 Discussions
    url: https://github.com/habhabhabs/inventag-aws/discussions
    about: Ask questions and discuss InvenTag with the community
  - name: 🔒 Security Issue
    url: https://github.com/habhabhabs/inventag-aws/security/advisories/new
    about: Report security vulnerabilities privately