// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Main documentation sidebar with organized navigation structure
  docsSidebar: [
    // Introduction and overview
    {
      type: 'doc',
      id: 'index',
      label: '🏠 Overview',
    },
    
    // Getting Started section
    {
      type: 'category',
      label: '🚀 Getting Started',
      collapsed: false,
      items: [
        'getting-started/introduction',
        'getting-started/quick-start',
        'getting-started/installation',
      ],
    },

    // User Guides section - auto-generated from user-guides directory
    {
      type: 'category',
      label: '📖 User Guides',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'user-guides',
        },
      ],
    },

    // Examples section
    {
      type: 'category',
      label: '📋 Examples',
      collapsed: true,
      items: [
        'examples/index',
        'examples/accounts-setup',
        'examples/cicd-integration',
        'examples/advanced-usage',
      ],
    },

    // Architecture & Technical Design section - auto-generated from architecture directory
    {
      type: 'category',
      label: '🏗️ Architecture',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'architecture',
        },
      ],
    },

    // Development section - auto-generated from development directory
    {
      type: 'category',
      label: '⚙️ Development',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'development',
        },
      ],
    },
  ],

  // Alternative sidebar configurations for different sections can be added here
  // This allows for flexible navigation based on user needs
  
  // Quick reference sidebar for advanced users
  quickReferenceSidebar: [
    {
      type: 'category',
      label: 'Quick Reference',
      items: [
        'user-guides/cli-user-guide',
        'user-guides/configuration-examples',
        'user-guides/troubleshooting-guide',
      ],
    },
  ],

  // Architecture-focused sidebar for technical users
  architectureSidebar: [
    {
      type: 'category',
      label: 'System Architecture',
      items: [
        'architecture/core-module-integration',
        'architecture/state-management',
        'architecture/template-framework',
        'architecture/service-enrichment',
        'architecture/bom-data-processor',
        'architecture/network-analysis',
        'architecture/cost-analysis',
        'architecture/tag-compliance',
      ],
    },
  ],
};

export default sidebars;
