// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Main documentation sidebar with organized navigation structure
  docsSidebar: [
    // Introduction and overview
    {
      type: 'doc',
      id: 'README',
      label: '🏠 Overview',
    },
    
    // Getting Started section - will be populated during content migration task
    // {
    //   type: 'category',
    //   label: '🚀 Getting Started',
    //   collapsed: false,
    //   items: [
    //     'getting-started/introduction',
    //     'getting-started/quick-start',
    //     'getting-started/installation',
    //   ],
    // },

    // User Guides section - auto-generated from user-guides directory
    {
      type: 'category',
      label: '📖 User Guides',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'user-guides',
        },
      ],
    },

    // Architecture & Technical Design section - auto-generated from architecture directory
    {
      type: 'category',
      label: '🏗️ Architecture',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'architecture',
        },
      ],
    },

    // Development section - auto-generated from development directory
    {
      type: 'category',
      label: '⚙️ Development',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'development',
        },
      ],
    },

    // Examples section - will be populated during content migration task
    // {
    //   type: 'category',
    //   label: '📋 Examples',
    //   collapsed: true,
    //   items: [
    //     'examples/accounts-setup',
    //     'examples/cicd-integration',
    //     'examples/advanced-usage',
    //   ],
    // },
  ],

  // Alternative sidebar configurations for different sections can be added here
  // This allows for flexible navigation based on user needs
  
  // Quick reference sidebar for advanced users
  quickReferenceSidebar: [
    {
      type: 'category',
      label: 'Quick Reference',
      items: [
        'user-guides/CLI_USER_GUIDE',
        'user-guides/CONFIGURATION_EXAMPLES',
        'user-guides/TROUBLESHOOTING_GUIDE',
      ],
    },
  ],

  // Architecture-focused sidebar for technical users
  architectureSidebar: [
    {
      type: 'category',
      label: 'System Architecture',
      items: [
        'architecture/CORE_MODULE_INTEGRATION',
        'architecture/STATE_MANAGEMENT',
        'architecture/TEMPLATE_FRAMEWORK',
        'architecture/SERVICE_ENRICHMENT',
        'architecture/BOM_DATA_PROCESSOR',
        'architecture/NETWORK_ANALYSIS',
        'architecture/COST_ANALYSIS',
        'architecture/TAG_COMPLIANCE',
      ],
    },
  ],
};

export default sidebars;
