// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Main documentation sidebar - auto-generated from docs folder structure
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar configuration can be used for specific organization
  // This will be configured in later tasks based on the actual documentation structure
};

export default sidebars;
